BEGIN;

CREATE TABLE IF NOT EXISTS public.areas_penal (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegacion_id integer NOT NULL,
    nombre text NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT areas_penal_delegacion_fk
        FOREIGN KEY (delegacion_id) REFERENCES public.delegaciones(id)
);

INSERT INTO public.areas_penal (id, delegacion_id, nombre, activo, created_at)
OVERRIDING SYSTEM VALUE
SELECT
    a.id,
    a.delegacion_id,
    a.nombre,
    true,
    now()
FROM public.areas a
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('public.areas_penal', 'id'),
    COALESCE((SELECT MAX(id) FROM public.areas_penal), 1),
    true
);

CREATE INDEX IF NOT EXISTS idx_areas_penal_delegacion
    ON public.areas_penal(delegacion_id);

CREATE INDEX IF NOT EXISTS idx_areas_penal_activo
    ON public.areas_penal(activo);

ALTER TABLE public.penal_asuntos
    DROP CONSTRAINT IF EXISTS penal_asuntos_area_hechos_fk;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'penal_asuntos_area_hechos_penal_fk'
          AND conrelid = 'public.penal_asuntos'::regclass
    ) THEN
        ALTER TABLE public.penal_asuntos
            ADD CONSTRAINT penal_asuntos_area_hechos_penal_fk
            FOREIGN KEY (area_hechos_id) REFERENCES public.areas_penal(id);
    END IF;
END;
$$;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.areas_penal TO app_seguimiento;
GRANT USAGE, SELECT ON SEQUENCE public.areas_penal_id_seq TO app_seguimiento;

COMMIT;
