BEGIN;

CREATE TABLE IF NOT EXISTS public.categorias_delito (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    descripcion text,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT categorias_delito_nombre_unique UNIQUE (nombre)
);

INSERT INTO public.categorias_delito (nombre, descripcion)
VALUES
    ('Apropiación indebida de bienes', 'Sustracción o disposición ilegítima de bienes bajo custodia o del Instituto'),
    ('Falsedad documental', 'Elaboración, uso o declaración con documentos/afirmaciones falsas'),
    ('Engaño patrimonial (fraude)', 'Obtención de lucro mediante engaño o aprovechamiento del error'),
    ('Delitos por hechos de corrupción / servidor público', 'Conductas ilícitas en el ejercicio de la función pública (Título Décimo CPF)'),
    ('Contra la salud / medicamentos', 'Adulteración/alteración de medicamentos y afines'),
    ('Defraudación / evasión de seguridad social', 'Delitos del capítulo de la LSS por omisión/evasión de cuotas y afines'),
    ('Contra el patrimonio (otros)', 'Daño, despojo, extorsión y afines sobre bienes del IMSS'),
    ('Delitos informáticos / datos', 'Acceso o afectación ilícita a sistemas y equipos de informática'),
    ('Fiscal', 'Delitos fiscales aplicables cuando el IMSS actúa como autoridad fiscal')
ON CONFLICT (nombre) DO UPDATE
SET descripcion = EXCLUDED.descripcion,
    activo = true;

ALTER TABLE public.delitos
    ADD COLUMN IF NOT EXISTS categoria_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'delitos_categoria_fk'
          AND conrelid = 'public.delitos'::regclass
    ) THEN
        ALTER TABLE public.delitos
            ADD CONSTRAINT delitos_categoria_fk
            FOREIGN KEY (categoria_id) REFERENCES public.categorias_delito(id);
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_delitos_categoria
    ON public.delitos(categoria_id);

UPDATE public.delitos d
SET categoria_id = c.id
FROM public.categorias_delito c
WHERE d.categoria_id IS NULL
  AND (
      (c.nombre = 'Engaño patrimonial (fraude)' AND lower(d.nombre) LIKE '%fraude%')
      OR (c.nombre = 'Falsedad documental' AND (
          lower(d.nombre) LIKE '%falsif%'
          OR lower(d.nombre) LIKE '%falsed%'
          OR lower(d.nombre) LIKE '%document%'
          OR lower(d.nombre) LIKE '%uso de documento%'
      ))
      OR (c.nombre = 'Contra el patrimonio (otros)' AND (
          lower(d.nombre) LIKE '%daño%'
          OR lower(d.nombre) LIKE '%dano%'
          OR lower(d.nombre) LIKE '%despojo%'
          OR lower(d.nombre) LIKE '%extorsi%'
          OR lower(d.nombre) LIKE '%patrimonio%'
      ))
      OR (c.nombre = 'Apropiación indebida de bienes' AND (
          lower(d.nombre) LIKE '%robo%'
          OR lower(d.nombre) LIKE '%apropi%'
          OR lower(d.nombre) LIKE '%sustrac%'
          OR lower(d.nombre) LIKE '%peculado%'
      ))
      OR (c.nombre = 'Delitos por hechos de corrupción / servidor público' AND (
          lower(d.nombre) LIKE '%corrup%'
          OR lower(d.nombre) LIKE '%servidor%'
          OR lower(d.nombre) LIKE '%cohecho%'
          OR lower(d.nombre) LIKE '%abuso de autoridad%'
          OR lower(d.nombre) LIKE '%ejercicio ilícito%'
      ))
      OR (c.nombre = 'Contra la salud / medicamentos' AND (
          lower(d.nombre) LIKE '%salud%'
          OR lower(d.nombre) LIKE '%medicament%'
          OR lower(d.nombre) LIKE '%adulter%'
          OR lower(d.nombre) LIKE '%alteraci%'
      ))
      OR (c.nombre = 'Defraudación / evasión de seguridad social' AND (
          lower(d.nombre) LIKE '%defraud%'
          OR lower(d.nombre) LIKE '%evas%'
          OR lower(d.nombre) LIKE '%cuota%'
          OR lower(d.nombre) LIKE '%seguridad social%'
      ))
      OR (c.nombre = 'Delitos informáticos / datos' AND (
          lower(d.nombre) LIKE '%inform%'
          OR lower(d.nombre) LIKE '%sistema%'
          OR lower(d.nombre) LIKE '%datos%'
          OR lower(d.nombre) LIKE '%acceso%'
      ))
      OR (c.nombre = 'Fiscal' AND (
          lower(d.nombre) LIKE '%fiscal%'
          OR lower(d.nombre) LIKE '%tribut%'
      ))
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.categorias_delito TO app_seguimiento;
GRANT USAGE, SELECT ON SEQUENCE public.categorias_delito_id_seq TO app_seguimiento;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.delitos TO app_seguimiento;

COMMIT;
