BEGIN;

-- =========================================================
-- MIGRACION 38 - FASES DE ACTUACION PENAL
-- Este script reinicia el catalogo dummy de etapas y, por
-- CASCADE, puede limpiar actuaciones asociadas a esas etapas.
-- Ejecutar solo en ambientes donde esa limpieza sea intencional.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.penal_catalogo_fases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etapa_id integer NOT NULL,
    nombre text NOT NULL,
    orden integer NOT NULL DEFAULT 1,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_catalogo_fases_etapa_nombre_unique UNIQUE (etapa_id, nombre),
    CONSTRAINT penal_catalogo_fases_etapa_fk
        FOREIGN KEY (etapa_id) REFERENCES public.penal_catalogo_etapas(id) ON DELETE CASCADE
);

TRUNCATE TABLE public.penal_catalogo_etapas RESTART IDENTITY CASCADE;

INSERT INTO public.penal_catalogo_etapas (nombre, orden, concluye_asunto, activo)
VALUES
    ('INVESTIGACIÓN INICIAL', 1, false, true),
    ('ETAPA INTERMEDIA', 2, false, true),
    ('JUICIO ORAL', 3, false, true),
    ('CONCLUIDO POR DETERMINACIÓN', 4, true, true),
    ('CONCLUIDO POR RESOLUCIÓN', 5, true, true);

INSERT INTO public.penal_catalogo_fases (etapa_id, nombre, orden, activo)
SELECT pce.id, fases.nombre, fases.orden, true
FROM public.penal_catalogo_etapas pce
JOIN (
    VALUES
        ('INVESTIGACIÓN INICIAL', 'Denuncia/querella', 1),
        ('INVESTIGACIÓN INICIAL', 'Integración de carpeta', 2),
        ('INVESTIGACIÓN INICIAL', 'Detención en flagrancia', 3),
        ('ETAPA INTERMEDIA', 'Audiencia inicial', 1),
        ('ETAPA INTERMEDIA', 'Formulación de acusación', 2),
        ('ETAPA INTERMEDIA', 'Descubrimiento probatorio', 3),
        ('ETAPA INTERMEDIA', 'Auto de apertura a juicio', 4),
        ('JUICIO ORAL', 'Desahogo de pruebas', 1),
        ('JUICIO ORAL', 'Alegatos', 2),
        ('JUICIO ORAL', 'Sentencia', 3),
        ('CONCLUIDO POR DETERMINACIÓN', 'Abstención de investigar', 1),
        ('CONCLUIDO POR DETERMINACIÓN', 'Archivo temporal', 2),
        ('CONCLUIDO POR DETERMINACIÓN', 'No ejercicio de la acción penal', 3),
        ('CONCLUIDO POR DETERMINACIÓN', 'Aplicación de criterio de oportunidad', 4),
        ('CONCLUIDO POR RESOLUCIÓN', 'Sentencia condenatoria', 1),
        ('CONCLUIDO POR RESOLUCIÓN', 'Sentencia absolutoria', 2),
        ('CONCLUIDO POR RESOLUCIÓN', 'Sobreseimiento', 3),
        ('CONCLUIDO POR RESOLUCIÓN', 'Acuerdo reparatorio/Salida alterna', 4)
) AS fases(etapa_nombre, nombre, orden)
    ON fases.etapa_nombre = pce.nombre
ON CONFLICT (etapa_id, nombre) DO UPDATE
SET
    orden = EXCLUDED.orden,
    activo = EXCLUDED.activo,
    updated_at = now();

ALTER TABLE public.penal_actuaciones
    ADD COLUMN IF NOT EXISTS fase_id integer;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'penal_actuaciones_fase_fk'
          AND conrelid = 'public.penal_actuaciones'::regclass
    ) THEN
        ALTER TABLE public.penal_actuaciones
            ADD CONSTRAINT penal_actuaciones_fase_fk
            FOREIGN KEY (fase_id) REFERENCES public.penal_catalogo_fases(id);
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_penal_catalogo_fases_etapa
    ON public.penal_catalogo_fases(etapa_id, orden, nombre);

CREATE INDEX IF NOT EXISTS idx_penal_actuaciones_fase
    ON public.penal_actuaciones(fase_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.penal_catalogo_fases TO app_seguimiento;
GRANT USAGE, SELECT ON SEQUENCE public.penal_catalogo_fases_id_seq TO app_seguimiento;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.penal_catalogo_etapas TO app_seguimiento;
GRANT USAGE, SELECT ON SEQUENCE public.penal_catalogo_etapas_id_seq TO app_seguimiento;

COMMIT;
