BEGIN;

-- =========================================================
-- MIGRACION 38 - MASC PENAL
-- Mecanismo Alternativo de Solucion de Controversias
-- =========================================================

CREATE TABLE IF NOT EXISTS public.penal_masc (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL UNIQUE,
    fecha_convenio date NOT NULL,
    descripcion text NOT NULL,
    cierra_carpeta boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by integer,
    updated_by integer,
    CONSTRAINT penal_masc_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE,
    CONSTRAINT penal_masc_created_by_fk
        FOREIGN KEY (created_by) REFERENCES public.usuarios(id),
    CONSTRAINT penal_masc_updated_by_fk
        FOREIGN KEY (updated_by) REFERENCES public.usuarios(id)
);

ALTER TABLE public.penal_actuaciones
    ADD COLUMN IF NOT EXISTS es_actuacion_cierre boolean NOT NULL DEFAULT false;

INSERT INTO public.penal_catalogo_fases (etapa_id, nombre, orden, activo)
SELECT pce.id, 'MASC', 5, true
FROM public.penal_catalogo_etapas pce
WHERE pce.nombre = 'CONCLUIDO POR RESOLUCIÓN'
ON CONFLICT (etapa_id, nombre) DO UPDATE
SET
    orden = EXCLUDED.orden,
    activo = EXCLUDED.activo,
    updated_at = now();

CREATE INDEX IF NOT EXISTS idx_penal_masc_asunto
    ON public.penal_masc(asunto_id);

CREATE INDEX IF NOT EXISTS idx_penal_actuaciones_cierre
    ON public.penal_actuaciones(asunto_id, es_actuacion_cierre)
    WHERE es_actuacion_cierre = TRUE;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.penal_masc TO app_seguimiento;
GRANT USAGE, SELECT ON SEQUENCE public.penal_masc_id_seq TO app_seguimiento;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.penal_actuaciones TO app_seguimiento;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.penal_catalogo_fases TO app_seguimiento;

COMMIT;
