-- =========================================================
-- BORRADOR DDL - NUEVO MODELO PENAL
-- Referencia de diseño. No ejecutar en producción sin revisión.
-- =========================================================

-- =========================================================
-- CATALOGOS PENAL
-- =========================================================

CREATE TABLE public.penal_catalogo_etapas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    orden integer NOT NULL DEFAULT 1,
    concluye_asunto boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_catalogo_etapas_nombre_unique UNIQUE (nombre)
);

CREATE TABLE public.penal_catalogo_estatus_solicitud (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL,
    orden integer NOT NULL DEFAULT 1,
    es_terminal boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_catalogo_estatus_solicitud_nombre_unique UNIQUE (nombre)
);

-- =========================================================
-- ASUNTO PENAL
-- =========================================================

CREATE TABLE public.penal_asuntos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delegacion_id integer NOT NULL,
    numero_carpeta text NOT NULL,
    anio_inicio integer NOT NULL,
    fecha_presentacion_denuncia date NOT NULL,
    delito_id integer NOT NULL,
    hechos_denunciante text NOT NULL,
    sin_cuantificar boolean NOT NULL DEFAULT true,
    cuantia_monto numeric(14,2),
    area_hechos_id integer,
    dato_relevante text,
    escenario_denunciante text NOT NULL,
    coadyuvancia boolean NOT NULL DEFAULT false,
    fecha_conocimiento_amp date,
    fecha_judicializacion date,
    determinacion_judicial text,
    estatus_general text NOT NULL DEFAULT 'TRAMITE',
    abogado_responsable_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    deleted_at timestamp with time zone,
    deleted_by integer,
    CONSTRAINT penal_asuntos_escenario_denunciante_check
        CHECK (escenario_denunciante IN ('IMSS', 'COADYUVANCIA', 'DISTINTO_IMSS')),
    CONSTRAINT penal_asuntos_estatus_general_check
        CHECK (estatus_general IN ('TRAMITE', 'CONCLUIDO')),
    CONSTRAINT penal_asuntos_cuantia_check
        CHECK (
            (sin_cuantificar = true AND cuantia_monto IS NULL)
            OR
            (sin_cuantificar = false)
        ),
    CONSTRAINT penal_asuntos_anio_inicio_check
        CHECK (anio_inicio >= 2000),
    CONSTRAINT penal_asuntos_numero_carpeta_unique UNIQUE (numero_carpeta),
    CONSTRAINT penal_asuntos_delegacion_fk
        FOREIGN KEY (delegacion_id) REFERENCES public.delegaciones(id),
    CONSTRAINT penal_asuntos_delito_fk
        FOREIGN KEY (delito_id) REFERENCES public.delitos(id),
    CONSTRAINT penal_asuntos_area_hechos_fk
        FOREIGN KEY (area_hechos_id) REFERENCES public.areas(id),
    CONSTRAINT penal_asuntos_abogado_responsable_fk
        FOREIGN KEY (abogado_responsable_id) REFERENCES public.usuarios(id),
    CONSTRAINT penal_asuntos_deleted_by_fk
        FOREIGN KEY (deleted_by) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_asuntos_delegacion ON public.penal_asuntos(delegacion_id);
CREATE INDEX idx_penal_asuntos_delito ON public.penal_asuntos(delito_id);
CREATE INDEX idx_penal_asuntos_estatus_general ON public.penal_asuntos(estatus_general);
CREATE INDEX idx_penal_asuntos_fecha_presentacion ON public.penal_asuntos(fecha_presentacion_denuncia);

-- =========================================================
-- PARTES INVOLUCRADAS
-- =========================================================

CREATE TABLE public.penal_denunciantes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    nombre text NOT NULL,
    es_imss boolean NOT NULL DEFAULT false,
    es_principal boolean NOT NULL DEFAULT false,
    es_coadyuvante boolean NOT NULL DEFAULT false,
    orden integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_denunciantes_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE
);

CREATE INDEX idx_penal_denunciantes_asunto ON public.penal_denunciantes(asunto_id, orden);

CREATE TABLE public.penal_probables_responsables (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    nombre text NOT NULL,
    es_qrr boolean NOT NULL DEFAULT false,
    orden integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_probables_responsables_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE
);

CREATE INDEX idx_penal_probables_responsables_asunto
    ON public.penal_probables_responsables(asunto_id, orden);

-- =========================================================
-- DOCUMENTO INICIAL DEL ASUNTO
-- =========================================================

CREATE TABLE public.penal_asunto_documentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    nombre_original text NOT NULL,
    nombre_guardado text NOT NULL,
    ruta_archivo text NOT NULL,
    mime_type text NOT NULL,
    tamano_bytes integer NOT NULL,
    observaciones text,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_asunto_documentos_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE,
    CONSTRAINT penal_asunto_documentos_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_asunto_documentos_asunto ON public.penal_asunto_documentos(asunto_id);

-- =========================================================
-- CONOCIMIENTO AMP
-- =========================================================

CREATE TABLE public.penal_conocimiento_amp (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    fecha_conocimiento_amp date NOT NULL,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT penal_conocimiento_amp_asunto_unique UNIQUE (asunto_id),
    CONSTRAINT penal_conocimiento_amp_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE,
    CONSTRAINT penal_conocimiento_amp_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

-- =========================================================
-- ACTUACIONES PENALES
-- =========================================================

CREATE TABLE public.penal_actuaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    fecha_actuacion date NOT NULL,
    etapa_id integer NOT NULL,
    descripcion text NOT NULL,
    texto_complementario_estatus text,
    referencia_carpeta text,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    deleted_at timestamp with time zone,
    deleted_by integer,
    CONSTRAINT penal_actuaciones_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE,
    CONSTRAINT penal_actuaciones_etapa_fk
        FOREIGN KEY (etapa_id) REFERENCES public.penal_catalogo_etapas(id),
    CONSTRAINT penal_actuaciones_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
    CONSTRAINT penal_actuaciones_deleted_by_fk
        FOREIGN KEY (deleted_by) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_actuaciones_asunto_fecha
    ON public.penal_actuaciones(asunto_id, fecha_actuacion DESC, id DESC);

CREATE TABLE public.penal_actuacion_documentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actuacion_id integer NOT NULL,
    nombre_original text NOT NULL,
    nombre_guardado text NOT NULL,
    ruta_archivo text NOT NULL,
    mime_type text NOT NULL,
    tamano_bytes integer NOT NULL,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_actuacion_documentos_actuacion_fk
        FOREIGN KEY (actuacion_id) REFERENCES public.penal_actuaciones(id) ON DELETE CASCADE,
    CONSTRAINT penal_actuacion_documentos_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_actuacion_documentos_actuacion
    ON public.penal_actuacion_documentos(actuacion_id);

-- =========================================================
-- REQUERIMIENTOS MINISTERIALES
-- =========================================================

CREATE TABLE public.penal_requerimientos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asunto_id integer NOT NULL,
    folio_referencia text,
    autoridad_emisora text NOT NULL,
    fecha_recepcion date NOT NULL,
    fecha_limite_atencion date NOT NULL,
    fecha_inicio_interno date,
    area_responsable_id integer,
    fase_actual text NOT NULL DEFAULT 'ALTA_INICIAL',
    created_by integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_requerimientos_fase_actual_check
        CHECK (fase_actual IN ('ALTA_INICIAL', 'SEGUIMIENTO_INTERNO', 'CONTESTACION_FINAL', 'CERRADO')),
    CONSTRAINT penal_requerimientos_asunto_fk
        FOREIGN KEY (asunto_id) REFERENCES public.penal_asuntos(id) ON DELETE CASCADE,
    CONSTRAINT penal_requerimientos_area_responsable_fk
        FOREIGN KEY (area_responsable_id) REFERENCES public.areas(id),
    CONSTRAINT penal_requerimientos_created_by_fk
        FOREIGN KEY (created_by) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_requerimientos_asunto ON public.penal_requerimientos(asunto_id, created_at DESC);
CREATE INDEX idx_penal_requerimientos_fase ON public.penal_requerimientos(fase_actual);

CREATE TABLE public.penal_requerimiento_documentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id integer NOT NULL,
    tipo_documento text NOT NULL,
    nombre_original text NOT NULL,
    nombre_guardado text NOT NULL,
    ruta_archivo text NOT NULL,
    mime_type text NOT NULL,
    tamano_bytes integer NOT NULL,
    observaciones text,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_requerimiento_documentos_tipo_check
        CHECK (tipo_documento IN ('INICIAL_FISCALIA', 'INTERNO_IMSS', 'CONTESTACION_ENVIADA', 'RESPUESTA_FISCALIA')),
    CONSTRAINT penal_requerimiento_documentos_requerimiento_fk
        FOREIGN KEY (requerimiento_id) REFERENCES public.penal_requerimientos(id) ON DELETE CASCADE,
    CONSTRAINT penal_requerimiento_documentos_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_requerimiento_documentos_req
    ON public.penal_requerimiento_documentos(requerimiento_id, tipo_documento);

CREATE TABLE public.penal_requerimiento_solicitudes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id integer NOT NULL,
    numero_orden integer NOT NULL DEFAULT 1,
    titulo text NOT NULL,
    descripcion text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_requerimiento_solicitudes_requerimiento_fk
        FOREIGN KEY (requerimiento_id) REFERENCES public.penal_requerimientos(id) ON DELETE CASCADE
);

CREATE INDEX idx_penal_requerimiento_solicitudes_req
    ON public.penal_requerimiento_solicitudes(requerimiento_id, numero_orden);

CREATE TABLE public.penal_requerimiento_solicitud_movimientos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id integer NOT NULL,
    estatus_solicitud_id integer NOT NULL,
    fecha_desahogo date,
    observaciones_documento text,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_req_sol_mov_solicitud_fk
        FOREIGN KEY (solicitud_id) REFERENCES public.penal_requerimiento_solicitudes(id) ON DELETE CASCADE,
    CONSTRAINT penal_req_sol_mov_estatus_fk
        FOREIGN KEY (estatus_solicitud_id) REFERENCES public.penal_catalogo_estatus_solicitud(id),
    CONSTRAINT penal_req_sol_mov_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_req_sol_mov_solicitud
    ON public.penal_requerimiento_solicitud_movimientos(solicitud_id, created_at DESC);

CREATE TABLE public.penal_requerimiento_solicitud_documentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_id integer NOT NULL,
    nombre_original text NOT NULL,
    nombre_guardado text NOT NULL,
    ruta_archivo text NOT NULL,
    mime_type text NOT NULL,
    tamano_bytes integer NOT NULL,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_req_sol_doc_movimiento_fk
        FOREIGN KEY (movimiento_id) REFERENCES public.penal_requerimiento_solicitud_movimientos(id) ON DELETE CASCADE,
    CONSTRAINT penal_req_sol_doc_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_req_sol_doc_movimiento
    ON public.penal_requerimiento_solicitud_documentos(movimiento_id);

CREATE TABLE public.penal_requerimiento_contestaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requerimiento_id integer NOT NULL,
    numero_orden integer NOT NULL DEFAULT 1,
    fecha_envio_respuesta date,
    fecha_respuesta_fiscalia date,
    observaciones_finales text,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_requerimiento_contestaciones_req_fk
        FOREIGN KEY (requerimiento_id) REFERENCES public.penal_requerimientos(id) ON DELETE CASCADE,
    CONSTRAINT penal_requerimiento_contestaciones_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_requerimiento_contestaciones_req
    ON public.penal_requerimiento_contestaciones(requerimiento_id, numero_orden);

CREATE TABLE public.penal_requerimiento_contestacion_documentos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contestacion_id integer NOT NULL,
    tipo_documento text NOT NULL,
    nombre_original text NOT NULL,
    nombre_guardado text NOT NULL,
    ruta_archivo text NOT NULL,
    mime_type text NOT NULL,
    tamano_bytes integer NOT NULL,
    usuario_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activo boolean NOT NULL DEFAULT true,
    CONSTRAINT penal_req_cont_doc_tipo_check
        CHECK (tipo_documento IN ('CONTESTACION_ENVIADA', 'RESPUESTA_FISCALIA')),
    CONSTRAINT penal_req_cont_doc_contestacion_fk
        FOREIGN KEY (contestacion_id) REFERENCES public.penal_requerimiento_contestaciones(id) ON DELETE CASCADE,
    CONSTRAINT penal_req_cont_doc_usuario_fk
        FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
);

CREATE INDEX idx_penal_req_cont_doc_contestacion
    ON public.penal_requerimiento_contestacion_documentos(contestacion_id, tipo_documento);
